version: '3.8'
services:
    paper:
        image: taygahoshi/paper:1.20.1-172
        container_name: paper
        volumes:
            - server-data:/home/serveruser/server
        stdin_open: true
        tty: true
        deploy:
            resources:
                limits:
                    memory: 4G

    haproxy:
        image: haproxy:latest
        container_name: paper-proxy
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - 25565:25565
            - 1936:1936

networks:
    default:
        name: minecraft-server
        driver: bridge

volumes:
  server-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./server-data
